trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: mcCntRegistry
  # azureSubscriptionEndpoint: djbinghamResourceManager
  containerImage: elm-lmp-web:$(Build.BuildId)
  system.debug: true
  testOutputDir: test-output

steps:
- task: Bash@3
  displayName: Build container images
  inputs:
    env:
      CONTAINER_IMAGE: $(containerImage)
    filePath: bin/docker/build
    targetType: inline

- task: Bash@3
  displayName: Test
  inputs:
    env:
      CONTAINER_IMAGE: $(containerImage)
      OUTPUT_DIR: $(testOutputDir)
    filePath: bin/docker/test
    targetType: inline

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: $(testOutputDir)/TEST-*.xml
    failTaskOnFailedTests: true
    testRunTitle: Unit-test

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: $(azureContainerRegistry)
    command: buildAndPush
    repository: elm-lmp-web
