trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: 'mcCntRegistry Connection'
  containerImage: elm-lmp-web:$(Build.BuildId)
  testOutputDir: test-output

steps:
- displayName: Build container images
  bash: bin/docker/build
  env:
    CONTAINER_IMAGE: $(containerImage)

- displayName: Test
  bash: bin/docker/test
  env:
    CONTAINER_IMAGE: $(containerImage)
    OUTPUT_DIR: $(testOutputDir)

- displayName: Publish test results
  task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: $(testOutputDir)/TEST-*.xml
    failTaskOnFailedTests: true
    testRunTitle: Unit-test

- displayName: Push production container image
  task: Docker@2
  inputs:
    containerRegistry: $(azureContainerRegistry)
    command: push
    repository: elm-lmp-web
