version: '3.7'

services:
  app:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-elm-apply
    networks:
      default:
        aliases:
          - ffc-elm-apply
