version: "3.4"

services:
  web:
    volumes:
      - "./index.js:/home/node/index.js"
      - "./client/:/home/node/client/"
      - "./server/:/home/node/server/"

  unit-test:
    volumes:
      - "./index.js:/home/node/index.js"
      - "./client/:/home/node/client/"
      - "./server/:/home/node/server/"
      - "./test/:/home/node/test/"
