version: '3.7'

services:
  app:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY:-171014905211.dkr.ecr.eu-west-2.amazonaws.com}
    image: ffc-elm-apply
    networks:
      default:
        aliases:
          - ffc-elm-apply
