version: "3.4"

services:
  pa11y:
    build:
      context: ./
      dockerfile: ./docker/pa11y.Dockerfile
    depends_on:
      - web

  unit-test:
    build:
      args:
        NODE_ENV: development
        PORT: ${PORT}
      context: ./
      target: development
    command: npm run test
    volumes:
      - "./.git/:/home/node/.git/"
      - "./test-output/:/home/node/test-output/"

  web:
    build:
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
      context: ./
      target: production
