apiVersion: skaffold/v1beta11
kind: Config

profiles:
- name: development
  activation:
  - command: dev
  patches:
  - op: replace
    path: /build/artifacts/0/docker/target
    value: development
  - op: replace
    path: /build/artifacts/1/docker/target
    value: development

build:
  artifacts:
  - image: mccntregistry.azurecr.io/elmlmp_web
    context: .
    docker:
      dockerfile: Dockerfile
      target: production
    sync:
      manual:
      - src: '**/*.js'
        dest: .
      - src: '**/*.njk'
        dest: .

  - image: mccntregistry.azurecr.io/elmlmp_api
    context: ../elm-api-boilerplate/
    docker:
      dockerfile: Dockerfile
      target: production
    sync:
      manual:
      - src: '**/*.js'
        dest: .

  local:
    push:

  tagPolicy:
    sha256: {}

deploy:
  helm:
    releases:
    - name: elm-lmp-web
      chartPath: helm/elm-lmp-web
      values:
        image: mccntregistry.azurecr.io/elmlmp_web
      valuesFiles:
      - helm/elm-lmp-web/values.yml
      - helm/elm-lmp-web/values.dev.yml
