version: "3.7"

services:
  pa11y:
    build:
      context: .
      target: pa11y
    command: npm run test:pa11y

  unit-test:
    build:
      args:
        NODE_ENV: development
      context: .
      target: development
    command: npm run test:unit
