version: "3.4"

services:
  pa11y:
    build:
      context: ../
      dockerfile: ./docker/pa11y.Dockerfile
    depends_on:
      - web

  unit-test:
    build:
      args:
        NODE_ENV: development
        PORT: ${PORT}
      context: ../
      target: development
    command: npm run test
    volumes:
      - "../server/:/home/node/server/"
      - "../test/:/home/node/test/"
      - "../test-output/:/home/node/test-output/"
