environment: production
image: ffc-elm-apply
name: ffc-elm-apply
namespace: ffc-elm
workstream: ffc-elm-apply

container:
  allowPrivilegeEscalation: false
  imagePullPolicy: IfNotPresent
  limitCpu: 80m
  limitMemory: 80Mi
  port: 3000
  readOnlyRootFilesystem: true
  requestMemory: 60Mi
  requestCpu: 60m
  staticCacheTimeoutMillis: 54000

deployment:
  imagePullSecret:
  minReadySeconds: 5
  priorityClassName: low
  redeployOnChange: update this field to force a change
  replicas: 1
  restartPolicy: Always
  runAsNonRoot: true
  runAsUser: 1000

ingress:
  class: nginx
  endpoint: ffc-elm-apply
  server: localhost

labels:
  component: apply

livenessProbe:
  initialDelaySeconds: 30
  failureThreshold: 3
  path: /healthz
  periodSeconds: 10
  port: 3000

readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 3
  path: /healthy
  periodSeconds: 10
  port: 3000

secret:
  auth:
  name: ffc-elm-apply-basic-auth
  type: Opaque

service:
  port: 443
  type: NodePort

serviceAccount:
  name: ffc-elm-apply-account
  roleArn:
