environment: development
image: mccntregistry.azurecr.io/elmlmp_web
name: elm-lmp-web
service:
  type: ClusterIP
  port: 80
container:
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
ingress:
  endpoint: elm-demo
replicaCount: 2
minReadySeconds: 5
