{{- if .Values.secret.auth }}
{{- include "ffc-helm-library.secret" (list . "ffc-elm-apply.basic-auth-secret") -}}
{{- end }}

{{- define "ffc-elm-apply.basic-auth-secret" -}}
data:
  auth: {{ .Values.secret.auth | quote }}
{{- end -}}
