{{- if .Values.auth }}
apiVersion: v1
data:
  auth: {{ quote .Values.auth }}
kind: Secret
metadata:
  name: ffc-elm-apply-basic-auth
  namespace: {{ quote .Values.namespace }}
type: Opaque
{{- end }}
