{{- include "ffc-helm-library.deployment" (list . "ffc-elm-apply.deployment") -}}

{{- define "ffc-elm-apply.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-elm-apply.container") }}
{{- end -}}
