environment: production
image: elm-apply
name: elm-apply
namespace: elm
auth:
imagePullSecret: myregistrykey

service:
  port: 443
  type: NodePort

container:
  priorityClassName: low
  imagePullPolicy: Always
  redeployOnChange: update this field to force a change
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  staticCacheTimeoutMillis: 54000

ingress:
  endPoint: elm-apply
  server: ffc.aws-int.defra.cloud

replicas: 1
minReadySeconds: 5
cookiePassword: passwordpasswordpasswordpasswordpassword

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
