apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.container.minReadySeconds }}
  template:
    metadata:
      annotations:
        redeployOnChange: "{{ .Values.container.redeployOnChange }}"
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.container.port }}"
          securityContext:
            runAsUser: {{ .Values.container.runAsUser }}
            runAsNonRoot: {{ .Values.container.runAsNonRoot }}
            readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
                memory: {{ .Values.container.requestMemory | quote }}
                cpu: {{ .Values.container.requestCpu | quote }}
            limits:
                memory: {{ .Values.container.limitMemory | quote }}
                cpu: {{ .Values.container.limitCpu | quote }}
