apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ .Values.service.name }}
spec:
  rules:
  - http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
