apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.service.name }}
status:
  loadBalancer: {}
